blank_issues_enabled: true
contact_links:
  - name: Questions, ideas, showcases and more
    url: https://github.com/mesa/mesa-geo/discussions
    about: Discuss Mesa-Geo, ask questions, share ideas, and showcase your projects
